### ISSUE TITLE
ArduinoISP Example should be renamed "Arduino_as_ISP" 

### ISSUE THREAD

**Issue by morrowsend** [arduino/arduino-examples#57]
### Describe the problem

I teach beginner programming and I ALWAYS have to make an excuse for the naming convention of "ArduinoISP" being the filename of the code that converts an Uno into an ISP programmer.  Because when selecting this programmer from the Tools menu, you cannot select "ArduinoISP" which has the same name, but is in fact a completely different device.  You must select "Arduino as ISP".

Even the official Arduino as ISP tutorial shows "ArduinoISP" as the example filename while telling you NOT to select ArduinoISP as the programmer device here: https://docs.arduino.cc/built-in-examples/arduino-isp/ArduinoISP#load-the-sketch

### To reproduce

Try to run the "ArduinoISP" example code on an uno, then select "ArduinoISP" on the tools menu and try to talk to it via Tools-->Upload using Programmer.  It will fail. Then change the programmer to "Arduino as ISP" and it will be able to talk to the programmer without issue.

### Expected behavior

Select the code from File-->Examples-->**_[11.Arduino_as_ISP](#)._**  Then select "Arduino as ISP" from the tools menu to use that device.

### The examples version

all versions

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-examples/issues?q=)
- [X] I verified the problem still occurs when using the latest version
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @morrowsend. Thanks for your report.

I agree that the naming collision between Arduino's unrelated retired [**ArduinoISP** ISP programmer product](https://docs.arduino.cc/retired/boards/arduino-isp) and the sketch name is very unfortunate.

I have personally seen quite a few instances of confusion that resulted from people selecting **Tools > Programmer > ArduinoISP** instead of **Tools > Programmer > Arduino as ISP** as would have been correct for their project. I have always suspected the sketch name might be a contributing factor (though I also think the two similarly named programmers would result in some confusion regardless).

Unfortunately I'm certain that renaming the sketch at this point would cause more harm than good. There is a tremendous number of tutorials, forum threads, etc. which explicitly mention the current sketch name.

So I will not be able to accept your proposal. However, other proposals for mitigating this issue in a non-breaking manner by more clearly communicating the appropriate programmer selection to the user are welcome.

**Comment by morrowsend** [comment]
Might a non-breaking solution be to simply add a new example "12. Arduino as ISP" with the same code?

**Comment by morrowsend** [comment]
Might a non-breaking solution be to simply add a new example "12. Arduino as ISP" with the same code?
